### ISSUE TITLE
Edit Story details of a story created by the user.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#13]
- Work in `routes/edit.js` to get the story details from the database and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).

- Update the story details as well.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sphoorthigaddam** [comment]
Could you assign this task to me @fabcodingzest

**Comment by fabcodingzest** [comment]
sure @sphoorthig
