### ISSUE TITLE
Edit the chapter created by a user.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#14]
- Work in `routes/edit.js` to get the chapter details from the database and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).

- Update the chapter details as well.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by czechyoungcoder** [comment]
I'm taking this issue.
