### ISSUE TITLE
Edit User settings for the user.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#15]
- Work in `routes/user.js` to get the user details from the database except for credentials like password and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).

- Update the user settings as well.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sphoorthigaddam** [comment]
Could you assign this task to me @fabcodingzest

**Comment by fabcodingzest** [comment]
sure @sphoorthig
