### ISSUE TITLE
Get public stories data

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#17]
- Work in `routes/index.js` to get the public stories from the database and send it as a response along with a message. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sonali-sawlani** [comment]
I will take this issue

**Comment by fabcodingzest** [comment]
okay @sonali-sawlani
