### ISSUE TITLE
Add story to reading list and library for respective routes.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#18]
- Work in `routes/user.js` to add a story to the reading list and user library of the user from the database and send it as a response along with a message. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).
- update reading list and library in respective routes by pushing the story Id in those lists of the user

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sonali-sawlani** [comment]
I am taking this
