### ISSUE TITLE
Add the feature to Create a story.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#4]
Work in `routes/create.js` to create a story and connect it with the corresponding user creating it. Created Stories Id is to be pushed inside myStories array in User Model while creating a story.

Story Model is already specified so refer to know the required variables in the database.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sonali-sawlani** [comment]
I will take this

**Comment by fabcodingzest** [comment]
Sure @sonali-sawlani
