### ISSUE TITLE
Add the feature to create a chapter.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#5]
Work in `routes/create.js` to create a chapter and connect it with the corresponding story. Created Chapter Id is to be pushed inside chapters array in Story Model while creating a chapter.

Chapter Model is already specified so refer to know the required variables in the database.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by czechyoungcoder** [comment]
I'd like to take this issue!

**Comment by fabcodingzest** [comment]
sure @czechyoungcoder 
All the best!
