### ISSUE TITLE
Get the story data and update the vote counter of a story.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#6]
- Work in `routes/story.js` to get the story data from the database and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).
- Also, handle the route to update the vote counter for a particular story.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by sphoorthigaddam** [comment]
@fabcodingzest Could you assign this to me.

**Comment by fabcodingzest** [comment]
Sure 
All the best @sphoorthig
