### ISSUE TITLE
Get the chapter data along with adding and deleting comments on a particular chapter.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#7]
- Work in `routes/story.js` to get the chapter data from the database and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).
- Also, handle the route to add and delete a comment for a particular chapter.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by czechyoungcoder** [comment]
I'm taking this issue.

**Comment by fabcodingzest** [comment]
I see you have self-assigned the issue to yourself  :rofl: , All the best! @czechyoungcoder
