### ISSUE TITLE
Get the stories search results according to query and tags.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/MagicReads_BE#8]
- Work in `routes/search.js` to get the stories data from the database and send it. Make sure to use the `.lean()` method for returning plain JavaScript objects instead of Mongoose documents and `.populate()` for populating a particular field (only those field can be populated that have `ref` key in their Data Model so do checkout models for reference).

- Right now we have two routes, one to search data according to the query and the other to search according to the tag(s). Manage the routes so both parameters can be optional and send the resulting stories from search.

If possible do not change other code without co-ordination as others might be working on it too.

All the best :smile: :+1:

**Comment by garimasingh22** [comment]
I'll take this:)

**Comment by fabcodingzest** [comment]
Sure @garimasingh22 
All the best!

**Comment by najimali** [comment]
Hey fab, please assign this task to me

**Comment by fabcodingzest** [comment]
sure @najimali 
All the best!
